# Site settings
title: Misoup
email: "ðŸŒðŸŒðŸŒ"
description: >
  Misoup found you! It palpitates.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://misoup.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
